### ISSUE TITLE
Необходимость проверки port

### ISSUE THREAD

**Issue by Lesh4** [aarekuha/rabbit-batch-consumer#1]
https://github.com/aarekuha/rabbit-batch-consumer/blob/83258bd295246c6c31281ed1f6890f67afcebcea/rabbit_batch_consumer.py#L105

Стоит ли проверять port, если он указан в параметрах функции со значением по умолчанию?

**Comment by aarekuha** [comment]
Стоит проверять - никто не запрещает вызов с передачей port=None. Эта проверка недорогая и выполняется только во время установления соединения.
