### ISSUE TITLE
Необходимость в [ ]

### ISSUE THREAD

**Issue by Lesh4** [aarekuha/rabbit-batch-consumer#2]
https://github.com/aarekuha/rabbit-batch-consumer/blob/83258bd295246c6c31281ed1f6890f67afcebcea/rabbit_batch_consumer.py#L125

Не совсем понял, зачем нужна такая конструкция. Если `routing_keys` пустой, то мы не попадем в цикл for.
Подскажешь для чего нужно делать так?

**Comment by aarekuha** [comment]
Если routing_keys не передан, то мы подписываемся без фильтрации и привязки - т.е. ко всем сообщениям
